### ISSUE TITLE
[FIX] 머지된것 중에 예상과 다른거 수정

### ISSUE THREAD

**Issue by hojeong26** [SoftwareEngineering-jnu1/AgileSupportProgram_FE#12]
## Description

- Sprint1 pr결과 이상한 부분 수정

## To Do

- [x] 헤더 로고 이미지 경로 수정
- [x] 폰트 적용
- [x] 라우팅 Outlet크기 수정

## ETC
- 머지해보니까 시작페이지가 틀어져서 수정해볼게요

**Comment by hojeong26** [comment]
혹시 동민님 노트북으로 실행했을 때 시작 페이지 안틀어지나요?? 은빈님도 봐주세요!

**Comment by dmsqls0704** [comment]
제가 봤을 때는 안틀어졌었는데 수정되었나요?

**Comment by hojeong26** [comment]
넵 동민님께서 수정하신대용
