### ISSUE TITLE
[PROBLEM] github action

### ISSUE THREAD

**Issue by hojeong26** [SoftwareEngineering-jnu1/AgileSupportProgram_FE#5]
## Description

- github action어떻게 해야될지 모르겠어요

## To Do

- [x] 프론트끼리 얘기
- [x] 해결

## ETC
- 제가 github action찾아보곤 있는데 어떻게 하는지 모르겠어서 한번 프론트끼리 얘기하고 찾아서 해결하든 교수님께 도움 요청하든 할까요...?

**Comment by rn1217** [comment]
넵 내일 컴퓨터그래픽스 수업 끝나고 잠깐 얘기해볼까요??

**Comment by hojeong26** [comment]
넵 전 시간 될 것 같아요
